documentation:
  - docs/*
  - docs/**/*

workflows:
  - .github/workflows/*
  - .github/workflows/**/*

deploy:
  - deploy/*
  - deploy/**/*

examples:
  - examples/*
  - examples/**/*

"area:dashboard":
  - pkg/server/*
  - pkg/server/**/*
  - pkg/web/*
  - pkg/web/**/*

"area:autoscaling":
  - pkg/prediction/*
  - pkg/prediction/**/*
  - pkg/metricprovider/*
  - pkg/controller/evpa/*
  - pkg/controller/ehpa/*
  
"area:algorithm":
  - pkg/prediction/*
  - pkg/prediction/**/*
  - pkg/predictor/*
  - pkg/predictor/**/*
  - pkg/controller/timeseriesprediction/*  

"area:recommendation":
  - pkg/recommend/*
  - pkg/recommend/**/*
  - pkg/recommendation/*
  - pkg/recommendation/**/*
  - pkg/controller/analytics/*
  - pkg/controller/recommendation/*
