
apiVersion: v1
kind: Namespace
metadata:
  name: crane-system

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: craned
  namespace: crane-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: craned
  namespace: crane-system
  labels:
    app: craned
spec:
  replicas: 1
  selector:
    matchLabels:
      app: craned
  template:
    metadata:
      labels:
        app: craned
    spec:
      serviceAccountName: craned
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
      containers:
        - name: craned
          image: docker.io/gocrane/craned:latest
          imagePullPolicy: IfNotPresent
          command:
            - /craned
            - -v=4