apiVersion: autoscaling.crane.io/v1alpha1
kind: AdvancedHorizontalPodAutoscaler
metadata:
  name: hpa-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wp-test-wordpress
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: External
      external:
        metric:
          name: pod_cpu_usage
        target:
          type: AverageValue
          averageValue: 30
  predictionConfig:
    predictionWindow: 600
    predictionAlgorithm:
      algorithmType: dsp
      dsp:
        sampleInterval: "60s"
        historyLength: "3d"
        estimators:
          fft:
            - marginFraction: "0.2"
              lowAmplitudeThreshold: "1.0"
              highFrequencyThreshold: "0.05"
              minNumOfSpectrumItems: 10
              maxNumOfSpectrumItems: 20